sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run -e CI=true tests

deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
