sudo: required
services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose run -e CI=true tests

after_success:
  - docker login --username=rfblue2@gmail.com --password=$HEROKU_TOKEN registry.heroku.com
  - docker build -t registry.heroku.com/sad-nyc-matching-staging/server .
  - docker push registry.heroku.com/sad-nyc-matching-staging/server
  - ./release.sh
